apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestdrive-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestdrive
  template:
    metadata:
      labels:
        app: requestdrive
    spec:
      containers:
      - name: requestdrive
        image: dimitartrj/requestdrive-service:latest
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: requestdrive-db-secret
                key: DB_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: requestdrive-db-secret
                key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: requestdrive-service
spec:
  type: ClusterIP
  selector:
    app: requestdrive
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
